@startuml
class World<extends BrokerSchema>
class WorldLoop<extends ServiceSchema>
class Redis<extends ServiceSchema>
class Mongo<extends ServiceSchema>
class PlayMode<extends ServiceSchema>
class State<extends ServiceSchema>

World --> WorldLoop
World --> Redis
World --> Mongo
World --> State
WorldLoop --> PlayMode
@enduml
